server:
  port: 8082
spring:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost/casas
    username: ${user}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
  jwt:
    secret: pPj7W5c8LsyP9+ldOwqQF/qEyzTV6WUJFSUgfsVOkXs=
    expiration: 36000000
