server:
  port: 8080
spring:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost/casas
    username: ${user}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update